version: '3.0'

services:

  ingress:
    build: nginx/
    image: barafu/ingress:1.0.0
    container_name: ingress
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Copenhagen
      - URL=baizley.com
      - SUBDOMAINS=www,moviequiz,companyhierarchy
      - VALIDATION=http
      - STAGING=false
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  data-shipper:
     build: fluentd/
     image: barafu/data-shipper:1.0.0
     container_name: data-shipper
     environment:
       - FLUENTD_CONF=baizley.conf
     env_file:
       - ~/Programming/baizley/environment.env
     ports:
       - 24224:24224

  ifyoulike:
    container_name: ifyoulike
    image: docker.pkg.github.com/baizley/ifyoulike/ifyoulike:1.0.0
    logging: 
      driver: fluentd
    env_file:
      - ~/Programming/ifyoulike/environment.env
    restart: unless-stopped

  movie-quiz:
    container_name: movie-quiz
    image: docker.pkg.github.com/baizley/movie-quiz/movie-quiz:1.0.0
    restart: unless-stopped

  company-hierarchy:
    container_name: company-hierarchy
    image: barafu/company-hierarchy:1.0.0
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: barafu/postgres:1.0.0
    command: postgres -c 'max_connections=11'
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=hierarchical company
      - POSTGRES_DB=company
    ports:
      - "5432:5432"

volumes:      
  db-data:

